### ISSUE TITLE
Feature: Support golang initialism / allow well-known headers

### ISSUE THREAD

**Issue by ccoVeille** [lasiar/canonicalheader#12]
Please support Go initialisms

https://go.dev/wiki/CodeReviewComments#initialisms
https://pkg.go.dev/github.com/Defacto2/releaser/initialism
https://staticcheck.io/docs/configuration/options/#initialisms

Maybe you could use [strcase](https://github.com/ettle/strcase/) for your tool
https://github.com/ettle/strcase/blob/main/initialism.go

**Comment by ccoVeille** [comment]
I would suggest you to use strcase and add your own Initialisms, based on these table

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

At least to add them in your unit tests

I can see at least 
- ETag
- DNT
- X-Request-ID

**Comment by ccoVeille** [comment]
I now realize your code relies on [net.http.CanonicalHeader](https://pkg.go.dev/net/http#CanonicalHeaderKey) …

So my problems is more at golang level maybe, but I don't think they would care about it.

What are your thoughts?

**Comment by lasiar** [comment]
Hi, @ccoVeille!

Thank you for interest to my linter!

I'm thinking of adding a config, where you can specify allow list.

I think this will be useful for your case.

**Comment by ccoVeille** [comment]
Great idea, thanks!

Wording is a pain. It's more an expected list for me than a allow list. 

I mwan I would expect your tool to ask me to fix `etaG` to `ETag` if I added `Etag` to the setting.

**Comment by lasiar** [comment]
My to do list:

- [ ] add const checks (now the linter check only string literal).
- [ ] implement this issue

I think it will be in the 2.0.0 version for backward compatibility.

**Comment by ccoVeille** [comment]
Noted, thanks for the follow up

**Comment by ccoVeille** [comment]
Here is a list of registered headers

https://www.iana.org/assignments/http-fields/http-fields.xhtml

It could help you to support some of them, even if it's only about example

**Comment by lasiar** [comment]
I fix it in version v1 without configuration, for backward compatibility

**Comment by ccoVeille** [comment]
It's worth trying yes

I identified the following patterns:

URL, URI, ETag, WWW, TTL, -ID (some have entityId)

Maybe strcase lib could help as I said

**Comment by lasiar** [comment]
I am planning to create a list from:

- https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
- https://www.iana.org/assignments/http-fields/http-fields.xhtml

**Comment by ccoVeille** [comment]
I could code it if you want, but I need a few days

**Comment by lasiar** [comment]
@ccoVeille, no, thanks :)

Today I will close for v1 (just skip, well-known headers)

**Comment by lasiar** [comment]
Done for v1!

Dependabot golangci-lint should update canonicalheader to 1.0.7 shortly

**Comment by ccoVeille** [comment]
I'm unsure I don't see the change listed here 🤔

https://github.com/lasiar/canonicalheader/releases/tag/v1.0.7

**Comment by ccoVeille** [comment]
@lasiar 1.0.7 point to 7da545705e7a345c0a78ed6e04866cc9a7683eed, so a commit that is older than a week, sounds strange

**Comment by lasiar** [comment]
@ccoVeille, Thanks a lot

Recreate release

**Comment by ccoVeille** [comment]
Oh you deleted and recreated tag. I have always thought that think people who does that are going to hell or at least will face angry people 🤣😂

I mean the CI might be confused, people who already fetched your code will have to delete the old tag locally before being able to fetch again.

**Comment by lasiar** [comment]
Only Dependabot golang-ci lint can update and it didn't do that.

This repo is not popular, this has its advantages 😊

**Comment by joshuatcasey** [comment]
Thanks for updating this - our application (https://pinniped.dev/) uses `X-XSS-Protection` and `X-DNS-Prefetch-Control` which are now on the allowlist!

**Comment by ccoVeille** [comment]
Dependabot just bumped version on golangci-lint

**Comment by lasiar** [comment]
Yes, I see :-(

**Comment by ccoVeille** [comment]
> Oh you deleted and recreated tag. I have always thought that think people who does that are going to hell or at least will face angry people 🤣😂
> 
> I mean the CI might be confused, people who already fetched your code will have to delete the old tag locally before being able to fetch again.

Told you ! 😅

**Comment by ccoVeille** [comment]
Shouldn't you close this issue, it's done, no?

@lasiar

**Comment by lasiar** [comment]
@ccoVeille 
No, I want to add configurable option allow headers

**Comment by xEricL** [comment]
> @ccoVeille No, I want to add configurable option allow headers

Looking forward to this. The linter is currently flagging `X-GitHub-Api-Version`, even though that is the correct header [according to GitHub docs](https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#x-github-api-version).

**Comment by lasiar** [comment]
Done!
