### ISSUE TITLE
Bug: strange suggestion in my code base

### ISSUE THREAD

**Issue by ccoVeille** [lasiar/canonicalheader#13]
Related to #12

Here is a list of header that were reported with your tool (v1.0.5)

- non-canonical header "X-Real-IP", instead use: "X-Real-Ip"
- non-canonical header "WWW-Authenticate", instead use: "Www-Authenticate"

These sounds strange, but I think it would be the same for ETag and others

**Comment by lasiar** [comment]
@ccoVeille, Thank you for issue

I will close this issue, and created PR for https://github.com/lasiar/canonicalheader/issues/12.

See https://github.com/lasiar/canonicalheader/issues/12#issuecomment-2074217092.

**Comment by ccoVeille** [comment]
Sure, thanks.
