### ISSUE TITLE
feature: GitHub action for typos

### ISSUE THREAD

**Issue by ccoVeille** [lasiar/canonicalheader#34]
You opened a few typos fix

https://github.com/lasiar/canonicalheader/pull/26
https://github.com/lasiar/canonicalheader/pull/30

I can help by setting up either typos or codespell actions, are you interested ?

https://github.com/marketplace/actions/typos-action
https://github.com/marketplace/actions/codespell-with-annotations

**Comment by lasiar** [comment]
Hi, @ccoVeille!

Oh, thanks!

If you don't mind, u can.
I prefer [typos-action](https://github.com/marketplace/actions/typos-action)
