### ISSUE TITLE
bug: false positives for abbreviations

### ISSUE THREAD

**Issue by thejan2009** [lasiar/canonicalheader#39]
There is a bunch of standard HTTP headers in use that contain all uppercase abbreviations, such as [`WWW-Authenticate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate), [`TE`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/TE), [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag).

Canonicallinter should not report them as invalid.

**Comment by ccoVeille** [comment]
Duplicate of #17

**Comment by thejan2009** [comment]
Aha, I had a look at the open issues and didn't find anything that looked like a bug report, so I opened it here :)

**Comment by ccoVeille** [comment]
> Aha, I had a look at the open issues and didn't find anything that looked like a bug report, so I opened it here :)

That's normal, I renamed it after you created yours, finding the issue name was misleading

**Comment by ccoVeille** [comment]
@thejan2009 bug has been fixed in latest version
