### ISSUE TITLE
Bump golangci-lint to latest

### ISSUE THREAD

**Issue by ccoVeille** [lasiar/canonicalheader#41]
You currently use 1.57.2

1.58.1 was released

You could use `version: latest` if you don't want to maintain it

https://github.com/marketplace/actions/golangci-lint

**Comment by lasiar** [comment]
I want to bump manually, because sometimes update linters can break CI.

Example: unused started working with anonymous functions

**Comment by ccoVeille** [comment]
OK, understood

**Comment by lasiar** [comment]
already updated!
