### ISSUE TITLE
Do you mind me suggesting a better set of option for .golangci-lint.yaml ?

### ISSUE THREAD

**Issue by ccoVeille** [lasiar/canonicalheader#42]
The file you used is great but somehow 3 years old. I have suggestion to do.

**Comment by ccoVeille** [comment]
I'm talking about https://olegk.dev/go-linters-configuration-the-right-version

**Comment by ccoVeille** [comment]
This gist is 3 years old and wasn't updated.

Many linters had been added to golangci-lint since it was provided.

I'll come back to you with proposal (I'm on phone now)

I might have to publish my own gist/dotfiles .

Stay in touch

**Comment by lasiar** [comment]
Can you review https://github.com/lasiar/canonicalheader/pull/46?

**Comment by lasiar** [comment]
close in https://github.com/lasiar/canonicalheader/pull/46?
