### ISSUE TITLE
v1.0.7 is corrupted

### ISSUE THREAD

**Issue by ldez** [lasiar/canonicalheader#43]
I think the tag has been recreated, so the content of this release is corrupted.
A version of a module should never be recreated.

<details>
<summary>The content of the module `github.com/lasiar/canonicalheader@v1.0.7`</summary>

```
.
├── analyzer.go
├── analyzer_test.go
├── cmd
│   └── canonicalheader
│       └── main.go
├── go.mod
├── go.sum
├── LICENCE
├── makefile
├── README.md
└── testdata
    └── src
        ├── alias
        │   ├── alias.go
        │   └── alias.go.golden
        ├── common
        │   ├── common.go
        │   └── common.go.golden
        ├── embedded
        │   ├── embedded.go
        │   └── embedded.go.golden
        ├── global
        │   ├── global.go
        │   ├── global_usage.go
        │   └── global_usage.go.golden
        └── struct
            ├── struct.go
            └── struct.go.golden

10 directories, 19 files
```

</details> 

<details>
<summary>The content of the current tag v1.0.7</summary>

```
.
├── analyzer.go
├── analyzer_test.go
├── cmd
│   ├── canonicalheader
│   │   └── main.go
│   └── initialismer
│       └── main.go
├── go.mod
├── go.sum
├── initialism.go
├── LICENCE
├── makefile
├── README.md
└── testdata
    └── src
        ├── alias
        │   ├── alias.go
        │   └── alias.go.golden
        ├── common
        │   ├── common.go
        │   └── common.go.golden
        ├── embedded
        │   ├── embedded.go
        │   └── embedded.go.golden
        ├── global
        │   ├── global.go
        │   ├── global_usage.go
        │   └── global_usage.go.golden
        ├── initialism
        │   └── initialism.go
        └── struct
            ├── struct.go
            └── struct.go.golden

12 directories, 22 files
```

</details> 

Also, [one of the PRs](https://github.com/lasiar/canonicalheader/pull/40) has been merged inside a branch `v1` and not inside `main`, I guess it was an attempt not to create a minor release without features.

<details>

```console
$ git lgr     
* a8968c0 N - (tag: v1.0.7, origin/v1, v1) fix: allow well-known headers
* 585255d N - fix: allow well-known headers
| * 57eee15 N - (origin/fix/v1/initialism) fix: allow well-known headers
| * f4b9653 N - fix: allow well-known headers
|/  
| * 2c04f9a N - (HEAD -> main, origin/main, origin/HEAD) fix(analyzer): check function assign.
| * d8d1e01 N - chore(deps): bump linter from 1.57 to 1.58
| * 1f24212 N - style(godot): change scope from default(declarations) to all
| * 809d5d1 N - chore(deps): bump golang.org/x/tools from 0.20.0 to 0.21.0
| * ba9ebc1 N - Add GitHub Typo Action
| * e73de50 N - Fix typos
| * b1b9464 N - ci(test): run test on macos and windows
| * 3ea58f4 N - docs(readme): added installation information
| * abbb991 N - chore(readme): typo license -> licence
| * 43d2880 N - chore: fix typo
| * e99ded0 N - ci(golangci): use official action
| * 64473de N - ci: add cache for test
| * 13c3470 N - chore(readme): rename action job
| * da5699c N - ci: split jobs
| * 8a78958 N - feat: add support more cases
|/
* 7da5457 N - ci(go): add tip version
* 60b3680 N - refactor(test): from slice of struct to slice of string
* 55ee7ac N - type(test): embeded -> embedded
* e89be98 N - chore(readme): add badges
* e12dda0 N - ci: update linter from 1.55.2 to 1.57.2
* 89e9983 N - (tag: v1.0.6) fix: added processing of more cases
* 8a73b10 N - chore(deps): bump actions/setup-go from 4 to 5
...
```

</details>

**Comment by lasiar** [comment]
@ldez, Hi!

Yes, v1.0.7 is recreating, is it problem?

About PR to v1:
The main branch will v2, and for golangci-lint 1.59.0.
I create the branch v1 for fixes bugs, for maintaining backward compatibility.

**Comment by ldez** [comment]
> Yes, v1.0.7 is recreating, is it problem?

Yes it's a major problem, a tag for a module should never be recreated (checksum).

My recommendations:
- merge `v1` inside `main`
- create a tag v1.1.0

**Comment by ldez** [comment]
A major version (like v2) should only be created if there are breaking changes.

Your linter doesn't have a configuration, so it cannot be breaking.

**Comment by lasiar** [comment]
If I create v1.0.8, this will solve the problem?

I'm planning:
all tags v1.x.x from the v1 branch
all tags v2.x.x from the v2 branch

**Comment by ldez** [comment]
Why do you want to create a major version?

**Comment by lasiar** [comment]
Add configuration: permit list for headers

**Comment by ldez** [comment]
So it's just a feature, no breaking changes here.

**Comment by ldez** [comment]
Configuration example:

```yml
canonicalheader:
  useDefaultExclusion: true
  Exclusion:
    - foo
    - bar
```

**Comment by ldez** [comment]
Maybe it's because you want to change the API, but the analyzer can have configuration without changing the public API: `Analyzer.Flags`

**Comment by lasiar** [comment]
I create v1.1.1 release and tag.

**Comment by lasiar** [comment]
@ldez, thanks!

**Comment by ldez** [comment]
Just for the information:
removing a tag is not enough to "remove" a module version, you should retract the version.

https://go.dev/ref/mod#go-mod-file-retract

In your context, I don't think you need to do it but I just wanted to share the good practices.

**Comment by lasiar** [comment]
Thanks!

I don't work on open source before, only private repo in private instance GitLab)


`canonicalheader@v1.1.1` include `golangci-lint@v1.58.2` or  `golangci-lint@v1.59.0`

In v1.56.1 `errcheck` updated from 1.6.3 to 1.7.0

**Comment by ldez** [comment]
I review every linter update and I decide based on the changes if it should be a part of the next minor or the next patch.

v1.1.1 will be in the next release patch.

https://github.com/golangci/golangci-lint/pull/4715

**Comment by ldez** [comment]
I consider the problem as fixed, thank you for your reactivity :heart:
